- hosts: all
  tasks: 
  - name: Adding Docker repository
    yum_repository:
       name: Docker
       description: Docker Repo
       baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
       gpgcheck: no

  - name: Installing Docker package
    package:
      name:  "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "starting docker service"
    service: 
     name: "docker"
     state: started
     enabled: yes

  - name: "installing python docker library"
    shell: "pip3 install docker"

  - name: "pulling docker image"
    docker_image: 
     name: "httpd" 
     source: pull

  - name: "making folder"
    file:
     path: /ansible
     state: directory

  - name: "copyting html file"
    copy: 
     src: "web.html"
     dest: "/ansible/"

  - name: "launching docker container"
    docker_container:
     name: "web_os" 
     image: httpd
     state: started
     exposed_ports:
     - "80"
     ports: 
     - "8222:80"
     volumes:
     - /ansible:/usr/local/apache2/htdocs/

